# 计分板刷新间隔(单位:秒)
scoreboardRefreshInterval: 3

# 是否在计分板显示序号 paper 1.20.3+支持
showSerialNo: false

# 是否开启更新提醒,建议开启
isCheckUpdate: true

# OP 登录时候是否发送更新提醒
isCheckUpdateToOpMsg: true

# 命令别名
commandAlias:
  sd: "psd toggle"