name: PlayerScoreboard
main: cn.handyplus.scoreboard.PlayerScoreboard
version: 1.0.3
author: handy
website: https://ricedoc.handyplus.cn/wiki/PlayerScoreboard/log/
api-version: 1.13
description: 玩家计分板
softdepend: [ PlaceholderAPI,AuthMe,CatSeedLogin,OauthLogin ]
folia-supported: true
commands:
  playerScoreboard:
    description: 玩家计分板
    aliases: [ psd ]
permissions:
  playerScoreboard.*:
    description: 玩家计分板所有权限
    children:
      playerScoreboard.reload: true
      playerScoreboard.toggle: true
  playerScoreboard.reload:
    description: 重载插件
    default: op
  playerScoreboard.toggle:
    description: 切换计分板显示
    default: true
  playerScoreboard.default:
    description: 默认计分板权限
    default: true